[project]
name = "cnam-intelligence-artificielle"
version = "0.1.0"
requires-python = "==3.14.3"

[dependency-groups]
dev = ["ruff==0.15.1", "ty==0.0.17"]

[tool.ruff]
target-version = "py314"
preview = true

[tool.ruff.format]
preview = true
